site_name: Matech Studios - OCTO
site_url: https://github.com/Matech-Studios/tech_docs/
site_description: Matech Studios presents "Office of the CTO"   
site_author: Facundo Ortiz

#nav:
#    - Home: index.md
#    - About: about.md
#    - 'Technical Doctrine': first_principles/firsts.md
#    - 'Confluence': 'https://matech.atlassian.net/wiki/spaces/MATECH/pages' 

theme: 
    name: material
    favicon: 'img/favicon.ico'
    features: 
        - tabs
    palette:
        scheme: preference # 'default' for light or 'slate' for dark
        primary: indigo
        accent: green  

# [update as needed] specify the URL to the GitHub repo for this site - included as link top right. URL must end with /
repo_url: https://github.com/Matech-Studios/tech_docs
# [update as needed] specify the text for repo link - included as link top right
repo_name: 'GitHub Matech'
# specify the relative path to markdown files in GitHub repo - typically does not need to be updated
# [update as needed] provides an edit link for each markdown page in site to make contribution to content easier
edit_uri: tree/master/docs/
# specify any links you want to include at right of footer
